version: 2.0

jobs:
  build:
    docker:
      - image: circleci/ruby:2.4-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
#       - checkout

#       - run: ls -la
      - run: echo "pretend to run build"

      - run:
          name: Run tests
          command: echo "pretend to run tests"

  deploy:
    machine:
        enabled: true
    working_directory: ~/circleci-demo-workflows
#    environment:
#      HEROKU_APP: "sleepy-refuge-55486"
    steps:
#       - checkout
      - run:
          name: Pretend Deployment
#          command: bash .circleci/setup-heroku.sh
          command: echo "pretend to deploy"
      - run:
          command: |
            echo "more"
            echo "pretend"
            echo "commands"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: feature-branch


