version: 2.0

jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - run: echo "pretend to run build"

  deploy:
    docker:
      - image: circleci/node:lts
    steps:
      - run: echo "pretend to run build"
      
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy
